Feat : Do not use AWS CLI command
env0/k8s-modules pull request #7
Opened 2022-01-26 14:55 UTC by GiliFaroEnv0

Solve issue https://github.com/env0/k8s-modules/issues/5

2022-01-26 15:08 UTC, eranelbaz commented on aws/autoscaler/main.tf
>  }
where `granularity \"1Minute\"`?

2022-01-26 15:44 UTC, yaronya requested changes
@GiliFaroEnv0 did you test it? Doesn't look like the autoscaler module has a `workers_group_defaults` attribute

I think it should be under `aws/eks/main.tf`

2022-02-01 19:19 UTC, GiliFaroEnv0 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Do not use AWS CLI command #5](https://trello.com/c/p4mbBNQt/5341-do-not-use-aws-cli-command-5)

2022-02-02 12:27 UTC, roni-frantchi commented
We'll have to look at a different approach - this one does not work

2022-02-02 12:27 UTC, closed without merging